services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: go-url-shortener-postgres
    ports:
      - 5433:5432
    networks:
      - go-url-shortener-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener

  postgres-test:
    image: postgres:16.4-alpine3.20
    container_name: go-url-shortener-postgres-test
    ports:
      - 5434:5432
    networks:
      - go-url-shortener-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener_test

  redis:
    image: redis:latest
    container_name: go-url-shortener-redis
    ports:
      - 6379:6379
    networks:
      - go-url-shortener-network

networks:
  go-url-shortener-network:
    driver: bridge
