services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: go-url-shortener-postgres
    ports:
      - 5433:5432
    networks:
      - go-url-shortener-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener

  redis:
    image: redis:latest
    container_name: go-url-shortener-redis
    ports:
      - 6379:6379
    networks:
      - go-url-shortener-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '8081:16686' # Jaeger UI
      - '14268'
      - '14250'
    networks:
      - go-url-shortener-network

networks:
  go-url-shortener-network:
    driver: bridge
