// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repo

import (
	"context"
)

type Querier interface {
	CreateHash(ctx context.Context, arg CreateHashParams) (ShortenedUrl, error)
	DeleteByHash(ctx context.Context, hash string) error
	DeleteByOriginalUrl(ctx context.Context, originalUrl string) error
	GetByHash(ctx context.Context, hash string) (ShortenedUrl, error)
	GetByOriginalUrl(ctx context.Context, originalUrl string) (ShortenedUrl, error)
}

var _ Querier = (*Queries)(nil)
