// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repo

import (
	"context"
)

type Querier interface {
	CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (ShortenedUrl, error)
}

var _ Querier = (*Queries)(nil)
