// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: short_url.sql

package repo

import (
	"context"
)

const createShortUrl = `-- name: CreateShortUrl :one
INSERT INTO shortened_urls (
  original_url,
  short_url
) VALUES (
  $1, $2
) RETURNING id, original_url, short_url, created_at, updated_at
`

type CreateShortUrlParams struct {
	OriginalUrl string `json:"original_url"`
	ShortUrl    string `json:"short_url"`
}

func (q *Queries) CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (ShortenedUrl, error) {
	row := q.db.QueryRow(ctx, createShortUrl, arg.OriginalUrl, arg.ShortUrl)
	var i ShortenedUrl
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
